List<Map<String, dynamic>> animals = [
  {
    "animal": "Cat",
    "canVaccinated": true,
    "canSterilized": true,
    "canHavePassport": true,
    "canHaveChip": true,
    "breeds": [
      'Domestic Cat',
      'Abyssinian',
      'American Bobtail',
      'American Curl',
      'American Shorthair',
      'American Wirehair',
      'Balinese - Javanese',
      'Bengal',
      'Birman',
      'Bombay',
      'British Shorthair',
      'Burmese',
      'Chartreux',
      'Cornish',
      'Devon Rex',
      'Egyptian Mau',
      'European Burmese',
      'Exotic Shorthair',
      'Havana Brown',
      'Himalayan',
      'Japanese Bobtail',
      'Korat',
      'LaPerm',
      'Maine Coon',
      'Manx',
      'Munchkin',
      'Norwegian Forest',
      'Ocicat',
      'Persian',
      'Peterbald',
      'Pixiebob',
      'Ragamuffin',
      'Ragdoll',
      'Russian Blue',
      'Savannah',
      'Scottish Fold',
      'Selkirk Rex',
      'Siamese',
      'Siberian',
      'Singapura',
      'Somali',
      'Sphynx',
      'Tonkinese',
      'Toyger',
      'Turkish Angora',
      'Turkish Van',
    ],
  },
  {
    "animal": "Cattle",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": true,
    "breeds": [
      'Angus',
      'Ayrshire',
      'Bonsmara',
      'Brahman',
      'Brangus',
      'Brown Swiss',
      'Canadienne',
      'Charolais',
      'Chianina',
      'Dexter',
      'Devon',
      'Friesian',
      'Galloway',
      'Gelbvieh',
      'Hereford',
      'Holstein',
      'Jersey',
      'Limousin',
      'Longhorn',
      'Maine-Anjou',
      'Milking Shorthorn',
      'Nguni',
      'Normande',
      'Piedmontese',
      'Salers',
      'Santa Gertrudis',
      'Scottish Highland',
      'Senepol',
      'Shorthorn',
      'Simmental',
      'Texas Longhorn',
      'Tuli',
      'Wagyu',
      'Other Breed',
    ],
  },
  {
    "animal": "Canary",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": false,
    "breeds": [
      'Other',
      "American Singer",
      "Border Fancy",
      "Fife Fancy",
      "Gloster Fancy",
      "Harz Roller",
      "Lizard",
      "Norwich",
      "Parisian Frilled",
      "Red Factor",
      "Spanish Timbrado",
    ],
  },
  {
    "animal": "Chicken",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": false,
    "breeds": [
      'Hybrid',
      'Ameraucana',
      'Ancona',
      'Andalusian',
      'Appenzeller Barthuhner',
      'Appenzeller Spitzhauben',
      'Araucana',
      'Australorp',
      'Barnevelder',
      'Belgian d\'Uccle',
      'Brahma',
      'Cochin',
      'Columbian Wyandotte',
      'Cuckoo Marans',
      'Dark Brahma',
      'Dark Cornish',
      'Delaware',
      'Dominique',
      'Dorking',
      'Easter Egger',
      'Egyptian Fayoumi',
      'Exchequer Leghorn',
      'Faverolles',
      'Fayoumi',
      'Friesian',
      'Frizzle',
      'Hamburg',
      'Houdan',
      'Japanese Bantam',
      'Jersey Giant',
      'Lakenvelder',
      'Langshan',
      'Lavender Orpington',
      'Legbar',
      'Light Brahma',
      'Marans',
      'Mille Fleur d\'Uccle',
      'Minorca',
      'New Hampshire Red',
      'New Hampshire',
      'Naked Neck',
      'Old English Game',
      'Orpington',
      'Phoenix',
      'Plymouth Rock',
      'Polish',
      'Rhode Island Red',
      'Rhodebar',
      'Rosecomb',
      'Sebright',
      'Serama',
      'Silkie',
      'Speckled Sussex',
      'Sultan',
      'Sumatra',
      'Sussex',
      'Swedish Flower Hen',
      'Thuringian',
      'Vorwerk',
      'Welsummer',
      'White Ameraucana',
      'White Cochin',
      'Wyandotte',
      'Yokohama',
    ],
  },
  {
    "animal": "Dog",
    "canVaccinated": true,
    "canSterilized": true,
    "canHavePassport": true,
    "canHaveChip": true,
    "breeds": [
      'Domestic Dog',
      'Affenpinscher',
      'Afghan Hound',
      'Airedale Terrier',
      'Akita',
      'Alaskan Malamute',
      'American English Coonhound',
      'American Eskimo',
      'American Foxhound',
      'American Staffordshire Terrier',
      'American Water Spaniel',
      'Anatolian Shepherd',
      'Australian Cattle',
      'Australian Shepherd',
      'Australian Terrier',
      'Basenji',
      'Basset Hound',
      'Beagle',
      'Bearded Collie',
      'Beauceron',
      'Bedlington Terrier',
      'Belgian Malinois',
      'Belgian Sheepdog',
      'Belgian Tervuren',
      'Bergamasco',
      'Berger Picard',
      'Bernese Mountain',
      'Bichon Frise',
      'Black and Tan Coonhound',
      'Black Russian',
      'Bloodhound',
      'Bluetick Coonhound',
      'Boerboel',
      'Border Collie',
      'Border Terrier',
      'Borzoi',
      'Boston Terrier',
      'Boxer',
      'Boykin Spaniel',
      'Briard',
      'Brittany',
      'Brussels Griffon',
      'Bull Terrier',
      'Bulldog',
      'Bullmastiff',
      'Cairn',
      'Canaan',
      'Cane Corso',
      'Cardigan Welsh Corgi',
      'Cavalier King Charles',
      'Cesky Terrier',
      'Chesapeake Bay Retriever',
      'Chihuahua',
      'Chinese Crested',
      'Chinese Shar-Pei',
      'Chinook',
      'Chow Chow',
      'Cirneco Dell\'Etna',
      'Clumber Spaniel',
      'Cocker Spaniel',
      'Collie',
      'Corgi',
      'Coton de Tulear',
      'Curly Coated Retriever',
      'Dachshund',
      'Dalmatian',
      'Dandie Dinmont Terrier',
      'Doberman',
      'Dogue De Bordeaux',
      'English Cocker',
      'English Foxhound',
      'English Setter',
      'English Springer',
      'English Toy',
      'Entlebucher Mountain',
      'Field',
      'Finnish Lapphund',
      'Finnish Spitz',
      'Flat Coated Retriever',
      'French Bulldog',
      'German Pinscher',
      'German Shepherd',
      'German Shorthaired Pointer',
      'German Wirehaired Pointer',
      'Giant Schnauzer',
      'Glen of Imaal Terrier',
      'Golden Retriever',
      'Gordon Setter',
      'Great Dane',
      'Great Pyrenees',
      'Great Swiss Mountain',
      'Harrier',
      'Havanese',
      'Ibizan Hound',
      'Icelandic Sheepdog',
      'Irish Red and White Setter',
      'Irish Setter',
      'Irish Terrier',
      'Irish Water',
      'Irish Wolfhound',
      'Italian Greyhound',
      'Japanese Chin',
      'Keeshond',
      'Kerry Blue Terrier',
      'Komondor',
      'Kuvasz',
      'Labrador',
      'Lagotto Romagnolo',
      'Lakeland',
      'Leonberger',
      'Lhasa',
      'Maltese',
      'Manchester Terrier',
      'Mastiff',
      'Miniature American Shepherd',
      'Miniature Bull Terrier',
      'Miniature Pinscher',
      'Miniature Schnauzer',
      'Neapolitan Mastiff',
      'Newfoundland',
      'Norfolk',
      'Norwegian Buhund',
      'Norwegian Elkhound',
      'Norwegian Lundehund',
      'Norwich Terrier',
      'Nova Scotia Duck Tolling',
      'Old English Sheepdog',
      'Otterhound',
      'Papillon',
      'Parson Russell',
      'Pekingese',
      'Petit Baset Griffon',
      'Pharaoh Hound',
      'Plot',
      'Pointer',
      'Polish Lowland',
      'Pomeranian',
      'Poodle',
      'Portuguese Podengo',
      'Portuguese Water',
      'Pug',
      'Puli',
      'Pyerenean',
      'Rat Terrier',
      'Redbone Coonhound',
      'Rhodesian',
      'Rottweiler',
      'Russell Terrier',
      'Russell',
      'Saint Bernard',
      'Saluki',
      'Samoyed',
      'Schipperke',
      'Scottish Deerhound',
      'Scottish Terrier',
      'Sealyham',
      'Shetland Sheepdog',
      'Shiba Inu',
      'Shih Tzu',
      'Siberian Husky',
      'Silky Terrier',
      'Skye Terrier',
      'Soft Coated Wheaten',
      'Spanish Water',
      'Spinone Italiano',
      'Staffordshire Bull',
      'Standard Schnauzer',
      'Sussex Spaniel',
      'Swedish Vallhund',
      'Tibetan Mastiff',
      'Tibetan Spaniel',
      'Tibetan Terrier',
      'Toy Fox',
      'Treeing Walker',
      'Treeing Walker Coonhound',
      'Vizsla',
      'Weimaraner',
      'Welsh Springer Spaniel',
      'Welsh Terrier',
      'West Highland',
      'West Highland White',
      'Whippet',
      'Wire Fox',
      'Wirehaired Pointing Griffon',
      'Wirehaired Vizsla',
      'Xoloitcuintli',
      'Yorkshire Terrier',
    ],
  },
  {
    "animal": "Donkey",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": true,
    "breeds": [
      'Algerian',
      'American Mammoth',
      'American Standard',
      'Andalusian',
      'Asinara',
      'Aures',
      'Balearic',
      'Baudet du Poitou',
      'Bourbonnais',
      'Catalan Pyrenean',
      'Catalonian',
      'Charentais',
      'Cotentin',
      'Leventine',
      'Mallorquin',
      'Majorera',
      'Miniature Mediterranean',
      'Miniature Sicilian',
      'Montmedy',
      'Norman',
      'Poitou',
      'Provence',
      'Sardinian',
      'Sicilian',
      'Spanish',
      'Tunisian',
      'Zamora',
      'Zamorano-Leones',
      'Other',
    ],
  },
  {
    "animal": "Duck",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": false,
    "breeds": [
      'Appleyard Duck',
      'Australian Spotted Duck',
      'Black Swedish Duck',
      'Call Duck',
      'Campbell Duck',
      'Cayuga Duck',
      'Dutch Hookbill Duck',
      'Indian Runner Duck',
      'Khaki Campbell Duck',
      'Magpie Duck',
      'Mallard Duck',
      'Muscovy Duck',
      'Pekin Duck',
      'Rouen Duck',
      'Saxony Duck',
      'Silver Appleyard Duck',
      'Welsh Harlequin Duck',
      'Other',
    ],
  },
  {
    "animal": "Fish",
    "canVaccinated": false,
    "canSterilized": false,
    "canHavePassport": false,
    "canHaveChip": false,
    "breeds": [
      'Other Species',
      'African Cichlid',
      'Angelfish',
      'Arowana',
      'Bala Shark',
      'Betta Fish',
      'Bichir',
      'Black Ghost Knife',
      'Black Skirt Tetra',
      'Bluefin Notho',
      'Bristlenose Pleco',
      'Celestial Pearl Danio',
      'Cherry Barb',
      'Clownfish',
      'Corydoras Catfish',
      'Discus Fish',
      'Dwarf Gourami',
      'Electric Blue Ram',
      'Electric Blue Acara',
      'Elephant Nose',
      'Flowerhorn',
      'Firemouth Cichlid',
      'Glass Catfish',
      'Glofish',
      'Goldfish',
      'Guppy',
      'Harlequin Rasbora',
      'Honey Gourami',
      'Japanese Fish',
      'Killifish',
      'Koi Fish',
      'Kuhki Loach',
      'Marbled Hatchetfish',
      'Molly',
      'Neon Tetra',
      'Ropefish',
      'Royal Farlowella Catfish',
      'Panda Corydoras',
      'Paradise',
      'Pea Puffers',
      'Pearl Gourami',
      'Pike Cichlids',
      'Plecostomus (Pleco)',
      'Platy',
      'Rainbow Fish',
      'Red Tail Shark',
      'Rosy Barb',
      'Siamese Algae Eater',
      'Swordtail',
      'Stiphodon Goby',
      'Threadfin Acara',
      'Tiger Barb',
      'Vampire Tetra',
      'Zebra Danio',
    ],
  },
  {
    "animal": "Guinea Pig",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": false,
    "breeds": [
      'Abyssinian',
      'American',
      'Coronet',
      'Peruvian',
      'Rex',
      'Silkie',
      'Skinny',
      'Teddy',
      'Texel',
      'White Crested',
      'Other',
    ],
  },
  {
    "animal": "Hamster",
    "canVaccinated": true,
    "canSterilized": true,
    "canHavePassport": true,
    "canHaveChip": false,
    "breeds": [
      'Allocricetulus',
      'Campbell\'s Dwarf',
      'Chinese',
      'Cricetulus',
      'Djungarian',
      'Dwarf',
      'Dwarf Winter White Russian',
      'European',
      'Phodopus',
      'Russian Winter White',
      'Russian Campbell',
      'Roborovski',
      'Syrian',
      'Mesocricetus',
      'Winter White',
      'Other',
    ],
  },
  {
    "animal": "Horse",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": true,
    "breeds": [
      'Akhal-Teke',
      'American Miniature Horse',
      'American Paint Horse',
      'American Quarter Horse',
      'Andalusian',
      'Appaloosa',
      'Arabian',
      'Belgian Draft Horse',
      'Clydesdale',
      'Connemara Pony',
      'Dartmoor Pony',
      'Dutch Warmblood',
      'Fell Pony',
      'Fjord Horse',
      'Friesian',
      'Gypsy Vanner',
      'Hackney Horse',
      'Hanoverian',
      'Holsteiner',
      'Icelandic Horse',
      'Irish Draught',
      'Lipizzan',
      'Lusitano',
      'Morgan Horse',
      'Mustang',
      'Norwegian Fjord',
      'Oldenburg',
      'Paso Fino',
      'Percheron',
      'Pony of the Americas',
      'Rocky Mountain Horse',
      'Shetland Pony',
      'Shire Horse',
      'Spanish Mustang',
      'Standardbred',
      'Suffolk Punch',
      'Swedish Warmblood',
      'Tennessee Walking Horse',
      'Thoroughbred',
      'Trakehner',
      'Welsh Pony',
      'Westphalian',
      'Other Breed',
    ],
  },
  {
    "animal": "Iguana",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": false,
    "breeds": [
      'Green Iguana',
      'Blue Iguana',
      'Rhinoceros Iguana',
      'Galapagos Land Iguana',
      'Marine Iguana',
      'Chuckwalla',
      'Spiny-Tailed Iguana',
      'Black Spiny-Tailed Iguana',
      'Other',
    ],
  },
  {
    "animal": "Mouse",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": false,
    "breeds": [
      'American Fancy Mouse',
      'Angora Mouse',
      'Black-Eyed White (BEW) Mouse',
      'Dutch Mouse',
      'Himalayan Mouse',
      'Long-Haired Mouse',
      'Rex Mouse',
      'Satin Mouse',
      'Siamese Mouse',
      'Texel Mouse',
      'Other',
    ],
  },
  {
    "animal": "Parrot",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": false,
    "breeds": [
      'African Grey',
      'Amazon',
      'Budgerigar (Budgie)',
      'Cockatiel',
      'Cockatoo',
      'Conure',
      'Eclectus',
      'Lovebird',
      'Macaw',
      'Parakeet',
      'Quaker',
      'Senegal',
      'Other',
    ],
  },
  {
    "animal": "Pig",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": true,
    "breeds": [
      'American Yorkshire',
      'Berkshire',
      'Duroc',
      'Gloucestershire Old Spot',
      'Hampshire',
      'Landrace',
      'Large Black',
      'Large White',
      'Mangalitsa',
      'Meishan',
      'Middle White',
      'Oxford Sandy and Black',
      'Pietrain',
      'Poland China',
      'Red Wattle',
      'Saddleback',
      'Tamworth',
      'Turopolje',
      'Vietnamese Potbelly',
      'Wessex Saddleback',
      'Other',
    ],
  },
  {
    "animal": "Pigeon",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": false,
    "breeds": [
      'American Giant Runt',
      'Archangel',
      'Barb',
      'Birmingham Roller',
      'Black Jacobin',
      'Bokhara Trumpeter',
      'Bruno de Jura',
      'Carneau',
      'Carrier',
      'Chinese Nasal Tuft',
      'Columba livia',
      'Crescent Moon',
      'Crested',
      'Cumulet',
      'Dutch Capuchine',
      'English Carrier',
      'English Pouter',
      'English Trumpeter',
      'Fantail',
      'Florentine',
      'Frillback',
      'Gaditano Pouter',
      'German Beauty Homer',
      'German Helmet',
      'Giant Homer',
      'Giant Runt',
      'Gloster Pouter',
      'Homing',
      'Indian Fantail',
      'Jacobin',
      'King',
      'Lahore',
      'Lebanese',
      'Ludwigshafen Tumbler',
      'Magpie',
      'Maltese',
      'Modena',
      'Muffed Helmet',
      'Norwich Cropper',
      'Old Dutch Capuchine',
      'Old German Owl',
      'Oriental Frill',
      'Parlour Tumbler',
      'Polish Lynx',
      'Pomeranian Pouter',
      'Portuguese Tumbler',
      'Priest',
      'Roller',
      'Russian Tumbler',
      'Saxon Field',
      'Scandaroon',
      'Show Racer',
      'Spanish Thief',
      'Strasser',
      'Suabian',
      'Syrian Coop',
      'Tumbler',
      'Utility Carneau',
      'Vienna Highflyer',
      'Other',
    ],
  },
  {
    "animal": "Rabbit",
    "canVaccinated": true,
    "canSterilized": true,
    "canHavePassport": true,
    "canHaveChip": true,
    "breeds": [
      'Alaskan',
      'Altex',
      'American',
      'American Chinchilla',
      'American Fuzzy Lop',
      'American Sable',
      'Angora',
      'Argente Bleu',
      'Argente Clair',
      'Argente Créme',
      'Argente De Champagne',
      'Argente Noir',
      'Argente St Hubert',
      'Armenian Marder',
      'Astrex',
      'Aurora Negro',
      'Baladi',
      'Bauscat',
      'Beige',
      'Belgian Hare',
      'Beveren',
      'Big Silver Marten',
      'Blanc De Bouscat',
      'Blanc De Hotot',
      'Blanc De Popielno',
      'Blue Of Ham',
      'Bourbonnais Grey',
      'Brazilian',
      'Britannia Petite',
      'British Giant',
      'Brown Chestnut Of Lorraine',
      'Caldes',
      'Californian',
      'Canadian Plush Lop',
      'Carmagnola Grey',
      'Cashmere Lop',
      'Champagne d\'Argent',
      'Chaudry',
      'Checkered Giant',
      'Chinchilla',
      'Chinchilla Giganta',
      'Cinnamon',
      'Continental Giant Coloured',
      'Continental Giant White',
      'Creme d\'Argent',
      'Criollo',
      'Cuban Brown',
      'Czech Red',
      'Czech Solver',
      'Czech Spot',
      'Czech White',
      'Dalmatian',
      'Deilenaar',
      'Dutch',
      'Dwarf Hotot',
      'Dwarf Lop',
      'Elfin',
      'Enderby Island',
      'English Angora',
      'English Lop',
      'English Spot',
      'Fauve De Bourgogne',
      'Flemish Giant',
      'Florida White',
      'Fox',
      'Fox Silver',
      'French Angora',
      'French Lop',
      'Gabali',
      'German Angora',
      'German Lop',
      'Giant Angora',
      'Giant Chinchilla',
      'Giant Havana',
      'Giant Marburger',
      'Giant Papillon',
      'Giant Silver',
      'Giant Smoke Pearl',
      'Giza White',
      'Golden Glavcot',
      'Gotland',
      'Gouwenaar',
      'Grey Pearl Of Halle',
      'Güzelçamlı',
      'Harlequin',
      'Harlequin Rex',
      'Havana',
      'Himalayan',
      'Holland Lop',
      'Hulstlander',
      'Hungarian Giant',
      'Isabella',
      'Jamora',
      'Japanese Dutch',
      'Japanese White',
      'Jersey Wooly',
      'Kabyle',
      'Lilac',
      'Lionhead',
      'Liptov Baldspotted',
      'Lynx',
      'Marburger Feh',
      'Mecklenburger Piebald',
      'Meissner Lop',
      'Mellerud',
      'Mini Cashmere',
      'Mini Lion Lop',
      'Mini Lop',
      'Mini Rex',
      'Mini Satin',
      'Miniature Lop',
      'Miniature Satin',
      'Moshtohor',
      'Netherland Dwarf',
      'New Zealand',
      'New Zealand Red',
      'New Zealand White',
      'Nitransky',
      'Opossum',
      'Orange',
      'Orylag',
      'Ørestad',
      'Palomino',
      'Perlfee',
      'Plush Lop',
      'Pointed Beveren',
      'Polish',
      'Rex',
      'Rhinelander',
      'Rhone',
      'Sa Phendula',
      'Sachsengold',
      'Sallander',
      'San Juan',
      'Satin',
      'Satin Angora',
      'Seperator',
      'Siamese Sable',
      'Siberian',
      'Silver',
      'Silver Fox',
      'Silver Marten',
      'Simenwar',
      'Slovenian',
      'Smoke Pearl',
      'Spanish Giant',
      'Squirrel',
      'Stone',
      'Sussex',
      'Swedish Fur',
      'Swedish Hare',
      'Swiss Fox',
      'Tadla',
      'Tan',
      'Tax-Xiber',
      'Teddy Dwarf',
      'Teddy Lop',
      'Thrianta',
      'Thuringer',
      'Tri-Colour Dutch',
      'Tri-Colour English',
      'Trønder',
      'V-Line',
      'Velveteen Lop',
      'Vienna Coloured',
      'Vienna White',
      'Wheaten',
      'Wheaten Lynx',
      'White Country',
      'Zemmouri',
      'Zika',
      'Other',
    ],
  },
  {
    "animal": "Sheep",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": true,
    "breeds": [
      'Other Breed',
      "Balwen",
      "Balwen Welsh Mountain",
      "Black Welsh Mountain",
      "Bluefaced Leicester",
      "Border Cheviot",
      "Border Leicester",
      "Boreray",
      "Castlemilk Moorit",
      "Charmoise Hill",
      "Cheviot",
      "Clun Forest",
      "Columbia",
      "Corriedale",
      "Cotswold",
      "Devon and Cornwall Longwool",
      "Dalesbred",
      "Dorper",
      "Dorset",
      "East Friesian",
      "Exmoor Horn",
      "Finnsheep",
      "Galway",
      "Gotland",
      "Hampshire",
      "Icelandic",
      "Jacob",
      "Karakul",
      "Kerry Hill",
      "Leicester Longwool",
      "Lleyn",
      "Lincoln",
      "Lincoln Longwool",
      "Manx Loaghtan",
      "Merino",
      "Navajo-Churro",
      "Norfolk Horn",
      "North Ronaldsay",
      "Oxford Down",
      "Polwarth",
      "Rambouillet",
      "Romney Marsh",
      "Romneys",
      "Ryeland",
      "Scottish Blackface",
      "Shetland",
      "Shropshire",
      "Soay",
      "Southdown",
      "Suffolk",
      "Targhee",
      "Teeswater",
      "Tunis",
      "Valais Blacknose",
      "Wensleydale",
      "Welsh Mountain",
      "Whitefaced Woodland",
      "Zwartbles",
    ],
  },
  {
    "animal": "Turkey",
    "canVaccinated": true,
    "canSterilized": false,
    "canHavePassport": true,
    "canHaveChip": false,
    "breeds": [
      "Black Spanish",
      "Bourbon Red",
      "Broad Breasted Bronze",
      "Broad Breasted White",
      "Buff",
      "Narragansett",
      "Royal Palm",
      "Slate",
      "Standard Bronze",
      "White Holland",
      'Other',
    ],
  },
];
